// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PCL;
using System.Diagnostics;

namespace HttpClientTest2
{
	public partial class MainViewController : UIViewController
	{
        private Module module;
        private ViewModel viewModel;

		public MainViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            this.module = new Module();
        }

        async partial void buttonClick (MonoTouch.Foundation.NSObject sender){
            Debug.WriteLine("BEFORE CLICK");
            ViewModel viewModel = await MyClass.Instance.GetViewModelAsync(new Request(){Name="MyName"});
            if(viewModel!=null){
                Debug.WriteLine("AFTER CLICK: " + viewModel.user);
            }else{
                Debug.WriteLine("FAILED");
            }
        }
	}
}
