// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PCL;
using System.Diagnostics;
using System.Net;

namespace HttpClientTest2
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Debug.WriteLine("Limit:" + ServicePointManager.DefaultConnectionLimit);
            //ServicePointManager.DefaultConnectionLimit = 2;
        }

        partial void oneGet (MonoTouch.Foundation.NSObject sender){
            GetAsync();
        }
        partial void twoGets (MonoTouch.Foundation.NSObject sender){
            for(int i=0;i<2;i++){
                GetAsync();
            }
        }
        partial void twentyGets (MonoTouch.Foundation.NSObject sender){
            for(int i=0;i<20;i++){
                GetAsync();
            }
        }

        async private void GetAsync(){
            Debug.WriteLine("BEFORE GETASYNC");
            ViewModel viewModel = await MyClass.Instance.GetAsync();
            if(viewModel!=null){
                Debug.WriteLine("AFTER GETASYNC: " + viewModel.user);
            }else{
                Debug.WriteLine("GETASYNC FAILED");
            }
        }

        partial void onePost (MonoTouch.Foundation.NSObject sender){
            PostAsync();
        }
        partial void twoPosts (MonoTouch.Foundation.NSObject sender){
            for(int i=0;i<2;i++){
                PostAsync();
            }
        }
        partial void twentyPosts (MonoTouch.Foundation.NSObject sender){
            for(int i=0;i<20;i++){
                PostAsync();
            }
        }
        async private void PostAsync(){
            Debug.WriteLine("BEFORE POSTASYNC");
            ViewModel viewModel = await MyClass.Instance.PostAsync(new Request(){Name="My name"});
            if(viewModel!=null){
                Debug.WriteLine("AFTER POSTASYNC: " + viewModel.user);
            }else{
                Debug.WriteLine("POSTASYNC FAILED");
            }
        }
	}
}
