// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PCL;
using System.Diagnostics;

namespace HttpClientTest2
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        partial void buttonClick (MonoTouch.Foundation.NSObject sender){
            GetViewModelAsync();
            //One request works most of the time, but two at the same time is a recipe for disaster
            GetViewModelAsync();
        }

        async private void GetViewModelAsync(){
            Debug.WriteLine("BEFORE GETVIEWMODELASYNC");
            ViewModel viewModel = await MyClass.Instance.GetViewModelAsync(new Request(){Name="MyName"});
            if(viewModel!=null){
                Debug.WriteLine("AFTER GETVIEWMODELASYNC: " + viewModel.user);
            }else{
                Debug.WriteLine("GETVIEWMODELASYNC FAILED");
            }
        }
	}
}
